name = "sentry-cloudflare-workers"
main = "workers/src/index.ts"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

# Secrets Store binding
[env.production]
vars = { ENVIRONMENT = "production" }

# KV Namespace bindings
[[kv_namespaces]]
binding = "TODOS"
id = "b92576ecf20d43ad8345de3f2bc5c1d4"
preview_id = "b92576ecf20d43ad8345de3f2bc5c1d4"