name = "sentry-cloudflare-workers"
main = "workers/src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespace bindings
[[kv_namespaces]]
binding = "TODOS"
id = "b92576ecf20d43ad8345de3f2bc5c1d4"